name: Generate PDF

on:
  push:
    paths:
      - 'litepaper/litepaper.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: pandoc litepaper/latex-includes.yaml litepaper/litepaper.md -F mermaid-filter urlcolor=cyan -o litepaper/litepaper.pdf
