name: Generate PDF

on:
  push:
    paths:
      - 'litepaper/litepaper.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc npm texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

    - name: Install Mermaid Filter
      run: npm install --global mermaid-filter

    - name: Convert Markdown to PDF
      run: pandoc latex-includes.yaml litepaper.md -F mermaid-filter --variable urlcolor=cyan -o litepaper.pdf

    - uses: stefanweifel/git-auto-commit-action@v4
      with:
        commit_message: Render PDF

